import Header from '@/layout/header/header';
import type { Metadata } from 'next';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Header />
        <div className="w-full container">{children}</div>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
